spring:
    datasource:
        url: jdbc:h2:mem:${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: false